#!/usr/bin/env bash

if [ -z "$GRAALVM_HOME" ]; then
    echo 'Please set GRAALVM_HOME'
    exit 1
fi

# Ensure Graal native-image program is installed
"$GRAALVM_HOME/bin/gu" install native-image

"$GRAALVM_HOME/bin/native-image" \
    -jar target/ooapi-tester-0.1.6.jar \
    -H:Name=ooapi-tester \
    -H:+ReportExceptionStackTraces \
    -H:+PrintClassInitialization \
    --enable-url-protocols=https \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g"